# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - nightly
matrix:
  allow_failures:
    - julia: nightly
git:
  depth: 999999
notifications:
  email: false
after_success:
  - julia -e 'import Pkg; Pkg.add("PhysicalConstant"); using Coverage; Coveralls.submit(process_folder()); Codecov.submit(process_folder())'
