environment:
  matrix:
  - julia_version: 0.7
  - julia_version: 1
  - julia_version: nightly

platform:
  - x86 # 32-bit
  - x64 # 64-bit

# # Uncomment the following lines to allow failures on nightly julia
# # (tests will run but not make your overall status red)
matrix:
  allow_failures:
    - julia_version: nightly

branches:
  only:
    - master
    - /release-.*/

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

install:
  - ps: iex ((new-object net.webclient).DownloadString("https://raw.githubusercontent.com/JuliaCI/Appveyor.jl/version-1/bin/install.ps1"))


import Pkg
Pkg.BinaryProvider.probe_platform_engines!(;verbose=true)
cmd = Pkg.BinaryProvider.gen_download_cmd("https://github.com/KristofferC/Crayons.jl/archive/v0.5.1.tar.gz", "Crayons.tar.gz")
run(cmd)
unpack = Pkg.BinaryProvider.gen_unpack_cmd("Crayons.tar.gz", "Crayons")
mkdir("Crayons")
run(unpack)

build_script:
  - echo "%JL_BUILD_SCRIPT%"
  - C:\julia\bin\julia -e "%JL_BUILD_SCRIPT%"
  - C:\julia\bin\julia -e "import Pkg; Pkg.BinaryProvider.probe_platform_engines!(;verbose=true)"
  - cmd = Pkg.BinaryProvider.gen_download_cmd("https://github.com/LaGuer/PhysicalConstant.jl/archive/v0.0.3.tar.gz", "PhysicalConstant.tar.gz")
  - unpack = Pkg.BinaryProvider.gen_unpack_cmd("PhysicalConstant.tar.gz", "PhysicalConstant")
#  - C:\julia\bin\julia -e "import Pkg; Pkg.clone("https://github.com/LaGuer/PhysicalConstant.jl.git")"
  - mkdir("PhysicalConstant")
  - run(unpack)
  - C:\julia\bin\julia -e "using InteractiveUtils; versioninfo();
#    using UUIDs;
#    before = read(\"Project.toml\", String);
#    after = replace(before, \"uuid = \\\"44cfe95a-1eb2-52ea-b672-e2afdf69b78f\\\"\" =>
#                            \"uuid = \\\"4d836010-47a6-11e8-12b2-0918962bae33\\\"\");
#    write(\"Project.toml\", before);
  - C:\julia\bin\julia -e "import Pkg; Pkg.update("PhysicalConstant")"
  - C:\julia\bin\julia -e "using PhysicalConstant.CODATA2019; CODATA2019.c_0"
  - C:\julia\bin\julia -e "import Pkg; Pkg.build()"

test_script:
  - echo "%JL_TEST_SCRIPT%"
  - C:\julia\bin\julia -e "%JL_TEST_SCRIPT%"
