desc = "Physical Constant CODATA2019."
keywords = ["physical", "constant", "codata"]
name = "PhysicalConstant"
uuid = "988cf3cc-0386-11e9-15da-fbc5ac71f155"
repo = "https://github.com/LaGuer/PhysicalConstant.jl.git"
author = "La Guer"
license = "MIT"
version = "v0.0.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

#[deps]
#Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
#Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
Julia = ">= v0.6"
