site_name:        PhysicalConstant.jl
repo_url:         https://github.com/LaGuer/PhysicalConstant.jl
site_description: Package for Physical Constants.
site_author:      LaGuer

theme: material
extra:
  palette:
    primary: 'indigo'
    accent:  'blue'

extra_css:
  - assets/Documenter.css

markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code
  - admonition

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

docs_dir: 'build'

pages:
- Home: index.md
- File formats: fileio.md
- 'License': LICENSE.md
